# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.0
  - 1.3
  - nightly
os:
  - linux
  - osx
  - windows
arch:
  - x64
  - x86
  - arm64
cache:
  directories:
    - ~/.julia/artifacts
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  exclude:
    - arch: x86
      os: osx
    - arch: arm64
      os: osx
    - arch: arm64
      os: windows
    - arch: arm64
      julia: nightly
  include:
    - stage: Documentation
      julia: 1
      script: |
        julia --project=docs -e '
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          using Documenter: DocMeta, doctest
          using BisectPy
          DocMeta.setdocmeta!(BisectPy, :DocTestSetup, :(using BisectPy); recursive=true)
          doctest(BisectPy)
          include("docs/make.jl")'
      after_success: skip
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Coveralls.submit(process_folder())'
